"""add tsv column for hybrid search

Revision ID: 0ed1c919bde0
Revises: 20af5d07d61c
Create Date: 2026-07-09 23:23:49.583969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ed1c919bde0'
down_revision: Union[str, Sequence[str], None] = '20af5d07d61c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_chunks', sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', chunk_text)", persisted=True), nullable=True))
    op.create_index('ix_candidate_chunks_tsv', 'candidate_chunks', ['tsv'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_candidate_chunks_tsv', table_name='candidate_chunks', postgresql_using='gin')
    op.drop_column('candidate_chunks', 'tsv')
    # ### end Alembic commands ###
