"""add file_hash for deduplication

Revision ID: b8db6fcefe16
Revises: 0ed1c919bde0
Create Date: 2026-07-09 23:45:04.548295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8db6fcefe16'
down_revision: Union[str, Sequence[str], None] = '0ed1c919bde0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('file_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_candidates_file_hash'), 'candidates', ['file_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidates_file_hash'), table_name='candidates')
    op.drop_column('candidates', 'file_hash')
    # ### end Alembic commands ###
