"""add structured_explanation to job_matches

Revision ID: bc0300d9b761
Revises: b8db6fcefe16
Create Date: 2026-07-11 12:30:58.145380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc0300d9b761'
down_revision: Union[str, Sequence[str], None] = 'b8db6fcefe16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_matches', sa.Column('structured_explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_matches', 'structured_explanation')
    # ### end Alembic commands ###
